apiVersion: apps/v1
kind: Deployment
metadata:
  name: vertex-deploy
  labels:
    app: myvertexappb
spec:
  replicas: 3
  selector:
      matchLabels:
         app: myvertexappb
  template:
     metadata:
       labels: 
         app: myvertexappb
     spec:
       containers:
        - name: myvertexapp-container
          image:  husenpatel/warbbimage20323:1
          ports:
            - containerPort: 8080
